# Generated by Django 3.0.5 on 2020-05-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookedAmbulance',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='AmbulanceType',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
