# Generated by Django 3.0.5 on 2020-06-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsapp', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfTravel', models.CharField(max_length=15)),
                ('timeOfTravel', models.CharField(max_length=15)),
                ('patientName', models.CharField(max_length=400)),
                ('sex', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=15)),
                ('ethnicity', models.CharField(max_length=20)),
                ('risks', models.CharField(max_length=1000)),
                ('pickUpAddress', models.TextField(max_length=1000)),
                ('pickUpWard', models.CharField(max_length=100)),
                ('pickUpContactName', models.CharField(max_length=200)),
                ('pickUpPhoneNO', models.CharField(max_length=15)),
                ('destinationAddress', models.CharField(max_length=1000)),
                ('destinationWard', models.CharField(max_length=100)),
                ('destinationContactName', models.CharField(max_length=200)),
                ('destinationPhoneNO', models.CharField(max_length=15)),
                ('escortRequirement', models.CharField(max_length=10)),
                ('hcaSex', models.CharField(max_length=30)),
                ('rmnSex', models.CharField(max_length=30)),
                ('rgnSex', models.CharField(max_length=30)),
                ('hcaQuantity', models.CharField(max_length=30)),
                ('rmnQuantity', models.CharField(max_length=30)),
                ('rgnQuantity', models.CharField(max_length=30)),
                ('date_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
