# Generated by Django 3.0.5 on 2020-05-21 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200521_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('NormalAmbulance', 'NormalAmbulance'), ('SecureAmbulance', 'SecureAmbulance'), ('HighSecureAmbulance', 'HighSecureAmbulance'), ('Ambulance<->Young&Child', 'Ambulance<->Young&Child'), ('WheelchairAmbulance', 'WheelchairAmbulance')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phoneNo', models.CharField(max_length=13, null=True)),
                ('emailId', models.CharField(max_length=220, null=True)),
                ('address', models.TextField(max_length=1000, null=True)),
                ('profilePic', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Served', 'Served'), ('Pending', 'Pending'), ('Out of Order', 'Out of Order')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('bookedAmbulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AmbulanceType')),
                ('customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CustomerModel')),
            ],
        ),
        migrations.AddField(
            model_name='ambulancetype',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
