# Generated by Django 3.0.5 on 2020-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200521_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingType',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Pre-Booking', 'Pre-Booking')], max_length=100, null=True),
        ),
    ]
